apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: monitoring
labels:
  app.kubernetes.io/instance: kube-prometheus
  app.kubernetes.io/name: alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      receiver: slack-notifier
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
    - name: 'slack-notifier'
      slack_configs:
      - channel: '#mlops-monitor'
        send_resolved: true
        username: 'Prometheus'
        api_url: 'https://hooks.slack.com/services/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'
