# job-failure-rules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: job-failure-rules
  namespace: monitoring
  labels:
    release: prometheus
    role: alert-rules
spec:
  groups:
    - name: job-failure-alerts
      rules:
        - alert: JobFailed
          expr: kube_job_status_failed{namespace="ml-serving"} > 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Job {{$labels.job_name}} failed"
            description: "Job {{$labels.job_name}} in namespace {{$labels.namespace}} has failed."
